load("@rules_java//java:defs.bzl", "java_test")

licenses(["notice"])

java_test(
    name = "PrfBasedDeriverKeyManagerTest",
    size = "small",
    srcs = ["PrfBasedDeriverKeyManagerTest.java"],
    deps = [
        "//proto:aes_gcm_java_proto",
        "//proto:common_java_proto",
        "//proto:hkdf_prf_java_proto",
        "//proto:prf_based_deriver_java_proto",
        "//proto:tink_java_proto",
        "//src/main/java/com/google/crypto/tink:insecure_secret_key_access",
        "//src/main/java/com/google/crypto/tink:key_manager",
        "//src/main/java/com/google/crypto/tink:registry_cluster",
        "//src/main/java/com/google/crypto/tink:registry_configuration",
        "//src/main/java/com/google/crypto/tink:tink_proto_keyset_format",
        "//src/main/java/com/google/crypto/tink/aead:x_cha_cha20_poly1305_parameters",
        "//src/main/java/com/google/crypto/tink/config:tink_config",
        "//src/main/java/com/google/crypto/tink/internal:key_manager_registry",
        "//src/main/java/com/google/crypto/tink/keyderivation:key_derivation_config",
        "//src/main/java/com/google/crypto/tink/keyderivation:keyset_deriver",
        "//src/main/java/com/google/crypto/tink/keyderivation:prf_based_key_derivation_key",
        "//src/main/java/com/google/crypto/tink/keyderivation:prf_based_key_derivation_parameters",
        "//src/main/java/com/google/crypto/tink/keyderivation/internal/test:prf_based_key_deriver_test_vectors",
        "//src/main/java/com/google/crypto/tink/prf:hkdf_prf_key",
        "//src/main/java/com/google/crypto/tink/prf:hkdf_prf_parameters",
        "//src/main/java/com/google/crypto/tink/prf:prf_config",
        "//src/main/java/com/google/crypto/tink/subtle:hex",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "PrfBasedKeyDerivationKeyProtoSerializationTest",
    size = "small",
    srcs = ["PrfBasedKeyDerivationKeyProtoSerializationTest.java"],
    deps = [
        "//proto:aes_cmac_prf_java_proto",
        "//proto:prf_based_deriver_java_proto",
        "//proto:tink_java_proto",
        "//proto:xchacha20_poly1305_java_proto",
        "//src/main/java/com/google/crypto/tink:configuration",
        "//src/main/java/com/google/crypto/tink:insecure_secret_key_access",
        "//src/main/java/com/google/crypto/tink:key",
        "//src/main/java/com/google/crypto/tink:parameters",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization",
        "//src/main/java/com/google/crypto/tink/aead:aead_config",
        "//src/main/java/com/google/crypto/tink/aead:x_cha_cha20_poly1305_key",
        "//src/main/java/com/google/crypto/tink/aead:x_cha_cha20_poly1305_parameters",
        "//src/main/java/com/google/crypto/tink/aead/subtle:x_cha_cha20_poly1305_proto_serialization",
        "//src/main/java/com/google/crypto/tink/internal:mutable_serialization_registry",
        "//src/main/java/com/google/crypto/tink/internal:proto_based_configuration_builder",
        "//src/main/java/com/google/crypto/tink/internal:tink_bug_exception",
        "//src/main/java/com/google/crypto/tink/internal/testing:asserts",
        "//src/main/java/com/google/crypto/tink/keyderivation:prf_based_key_derivation_key",
        "//src/main/java/com/google/crypto/tink/keyderivation:prf_based_key_derivation_parameters",
        "//src/main/java/com/google/crypto/tink/keyderivation/internal:prf_based_key_derivation_key_proto_serialization",
        "//src/main/java/com/google/crypto/tink/prf:aes_cmac_prf_key",
        "//src/main/java/com/google/crypto/tink/prf:aes_cmac_prf_parameters",
        "//src/main/java/com/google/crypto/tink/prf:prf_config",
        "//src/main/java/com/google/crypto/tink/prf:prf_parameters",
        "//src/main/java/com/google/crypto/tink/prf/subtle:aes_cmac_prf_proto_serialization",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "PrfBasedDeriverSecondTest",
    size = "small",
    srcs = ["PrfBasedDeriverSecondTest.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:insecure_secret_key_access",
        "//src/main/java/com/google/crypto/tink:key",
        "//src/main/java/com/google/crypto/tink:key_status",
        "//src/main/java/com/google/crypto/tink:registry_cluster",
        "//src/main/java/com/google/crypto/tink:registry_configuration",
        "//src/main/java/com/google/crypto/tink/aead:aes_gcm_key",
        "//src/main/java/com/google/crypto/tink/aead:aes_gcm_parameters",
        "//src/main/java/com/google/crypto/tink/config:tink_config",
        "//src/main/java/com/google/crypto/tink/internal:tink_bug_exception",
        "//src/main/java/com/google/crypto/tink/internal:util",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_mac_config",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_signature_config",
        "//src/main/java/com/google/crypto/tink/keyderivation:key_derivation_config",
        "//src/main/java/com/google/crypto/tink/keyderivation:keyset_deriver",
        "//src/main/java/com/google/crypto/tink/keyderivation:prf_based_key_derivation_key",
        "//src/main/java/com/google/crypto/tink/keyderivation:prf_based_key_derivation_parameters",
        "//src/main/java/com/google/crypto/tink/keyderivation/internal/test:prf_based_key_deriver_test_vectors",
        "//src/main/java/com/google/crypto/tink/prf:hkdf_prf_key",
        "//src/main/java/com/google/crypto/tink/prf:hkdf_prf_parameters",
        "//src/main/java/com/google/crypto/tink/subtle:hex",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_conscrypt_conscrypt_openjdk_uber",
    ],
)

java_test(
    name = "PrfBasedKeyDeriverTest",
    size = "small",
    srcs = ["PrfBasedKeyDeriverTest.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:aead",
        "//src/main/java/com/google/crypto/tink:insecure_secret_key_access",
        "//src/main/java/com/google/crypto/tink:key",
        "//src/main/java/com/google/crypto/tink:parameters",
        "//src/main/java/com/google/crypto/tink:secret_key_access",
        "//src/main/java/com/google/crypto/tink/aead:aes_gcm_key",
        "//src/main/java/com/google/crypto/tink/aead:aes_gcm_parameters",
        "//src/main/java/com/google/crypto/tink/aead:x_cha_cha20_poly1305_parameters",
        "//src/main/java/com/google/crypto/tink/config:tink_config",
        "//src/main/java/com/google/crypto/tink/internal:mutable_key_derivation_registry",
        "//src/main/java/com/google/crypto/tink/internal:mutable_primitive_registry",
        "//src/main/java/com/google/crypto/tink/internal:primitive_constructor",
        "//src/main/java/com/google/crypto/tink/internal:primitive_registry",
        "//src/main/java/com/google/crypto/tink/internal:tink_bug_exception",
        "//src/main/java/com/google/crypto/tink/internal:util",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_mac_config",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_signature_config",
        "//src/main/java/com/google/crypto/tink/keyderivation:key_derivation_config",
        "//src/main/java/com/google/crypto/tink/keyderivation:prf_based_key_derivation_key",
        "//src/main/java/com/google/crypto/tink/keyderivation:prf_based_key_derivation_parameters",
        "//src/main/java/com/google/crypto/tink/keyderivation/internal:key_deriver",
        "//src/main/java/com/google/crypto/tink/keyderivation/internal:prf_based_key_deriver",
        "//src/main/java/com/google/crypto/tink/keyderivation/internal/test:prf_based_key_deriver_test_vectors",
        "//src/main/java/com/google/crypto/tink/prf:hkdf_prf_key",
        "//src/main/java/com/google/crypto/tink/prf:hkdf_prf_parameters",
        "//src/main/java/com/google/crypto/tink/prf:prf_key",
        "//src/main/java/com/google/crypto/tink/prf:prf_parameters",
        "//src/main/java/com/google/crypto/tink/subtle:aes_gcm_jce",
        "//src/main/java/com/google/crypto/tink/subtle:hex",
        "//src/main/java/com/google/crypto/tink/subtle/prf:streaming_prf",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_errorprone_error_prone_annotations",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_conscrypt_conscrypt_openjdk_uber",
    ],
)

java_test(
    name = "KeysetDeriverWrapperTest",
    size = "small",
    srcs = ["KeysetDeriverWrapperTest.java"],
    deps = [
        "//proto:common_java_proto",
        "//proto:hkdf_prf_java_proto",
        "//proto:prf_based_deriver_java_proto",
        "//proto:tink_java_proto",
        "//proto:xchacha20_poly1305_java_proto",
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:insecure_secret_key_access",
        "//src/main/java/com/google/crypto/tink:key",
        "//src/main/java/com/google/crypto/tink:key_status",
        "//src/main/java/com/google/crypto/tink:registry_cluster",
        "//src/main/java/com/google/crypto/tink:registry_configuration",
        "//src/main/java/com/google/crypto/tink:tink_proto_keyset_format",
        "//src/main/java/com/google/crypto/tink/aead:aead_config",
        "//src/main/java/com/google/crypto/tink/aead:aes_gcm_key",
        "//src/main/java/com/google/crypto/tink/aead:aes_gcm_parameters",
        "//src/main/java/com/google/crypto/tink/daead:deterministic_aead_config",
        "//src/main/java/com/google/crypto/tink/internal:mutable_key_derivation_registry",
        "//src/main/java/com/google/crypto/tink/internal:mutable_primitive_registry",
        "//src/main/java/com/google/crypto/tink/internal:primitive_constructor",
        "//src/main/java/com/google/crypto/tink/internal:tink_bug_exception",
        "//src/main/java/com/google/crypto/tink/internal:util",
        "//src/main/java/com/google/crypto/tink/keyderivation:keyset_deriver",
        "//src/main/java/com/google/crypto/tink/keyderivation:prf_based_key_derivation_key",
        "//src/main/java/com/google/crypto/tink/keyderivation:prf_based_key_derivation_parameters",
        "//src/main/java/com/google/crypto/tink/keyderivation/internal:key_deriver",
        "//src/main/java/com/google/crypto/tink/keyderivation/internal:keyset_deriver_wrapper",
        "//src/main/java/com/google/crypto/tink/keyderivation/internal:prf_based_key_derivation_key_proto_serialization",
        "//src/main/java/com/google/crypto/tink/keyderivation/internal:prf_based_key_deriver",
        "//src/main/java/com/google/crypto/tink/keyderivation/internal/test:prf_based_key_deriver_test_vectors",
        "//src/main/java/com/google/crypto/tink/mac:mac_config",
        "//src/main/java/com/google/crypto/tink/prf:hkdf_prf_key",
        "//src/main/java/com/google/crypto/tink/prf:hkdf_prf_parameters",
        "//src/main/java/com/google/crypto/tink/prf:prf_config",
        "//src/main/java/com/google/crypto/tink/signature:signature_config",
        "//src/main/java/com/google/crypto/tink/streamingaead:streaming_aead_config",
        "//src/main/java/com/google/crypto/tink/subtle:hex",
        "//src/main/java/com/google/crypto/tink/subtle/prf:streaming_prf",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_conscrypt_conscrypt_openjdk_uber",
    ],
)

java_test(
    name = "KeyDerivationConfig2026Test",
    size = "small",
    srcs = ["KeyDerivationConfig2026Test.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:insecure_secret_key_access",
        "//src/main/java/com/google/crypto/tink:parameters",
        "//src/main/java/com/google/crypto/tink:registry_cluster",
        "//src/main/java/com/google/crypto/tink:tink_proto_keyset_format",
        "//src/main/java/com/google/crypto/tink:tink_proto_parameters_format",
        "//src/main/java/com/google/crypto/tink/aead:aes_gcm_key_manager",
        "//src/main/java/com/google/crypto/tink/aead:aes_gcm_parameters",
        "//src/main/java/com/google/crypto/tink/config/internal:tink_fips_util",
        "//src/main/java/com/google/crypto/tink/keyderivation:keyset_deriver",
        "//src/main/java/com/google/crypto/tink/keyderivation:prf_based_key_derivation_key",
        "//src/main/java/com/google/crypto/tink/keyderivation:prf_based_key_derivation_parameters",
        "//src/main/java/com/google/crypto/tink/keyderivation/internal:key_derivation_config2026",
        "//src/main/java/com/google/crypto/tink/keyderivation/internal/test:prf_based_key_deriver_test_vectors",
        "//src/main/java/com/google/crypto/tink/prf:hkdf_prf_key",
        "//src/main/java/com/google/crypto/tink/prf:hkdf_prf_parameters",
        "//src/main/java/com/google/crypto/tink/subtle:hex",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)
