// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
////////////////////////////////////////////////////////////////////////////////

package com.google.crypto.tink.internal;

import com.google.crypto.tink.ProtoKeySerialization;
import com.google.crypto.tink.proto.KeyData;
import com.google.crypto.tink.proto.OutputPrefixType;
import com.google.crypto.tink.util.Bytes;
import java.security.GeneralSecurityException;
import javax.annotation.Nullable;

/**
 * This class provides conversions to Tink classes and enums which are in the public API to classes
 * and enums generated by the Protobuf compiler.
 *
 * <p>As a long term goal of Tink, we do not want to have code which the Protobuf compiler generates
 * in the public API. Such code is more difficult to use externally to Google, for example with
 * Maven. However, at least for some time we still will need to use these classes within Tink, hence
 * we use such conversion code which must not be used outside of Tink as it may be removed at any
 * time.
 */
public final class ProtoConversions {
  public static KeyData.KeyMaterialType toProto(ProtoKeySerialization.KeyMaterialType type)
      throws GeneralSecurityException {
    if (type.equals(ProtoKeySerialization.KeyMaterialType.UNKNOWN_KEYMATERIAL)) {
      return KeyData.KeyMaterialType.UNKNOWN_KEYMATERIAL;
    }
    if (type.equals(ProtoKeySerialization.KeyMaterialType.SYMMETRIC)) {
      return KeyData.KeyMaterialType.SYMMETRIC;
    }
    if (type.equals(ProtoKeySerialization.KeyMaterialType.ASYMMETRIC_PRIVATE)) {
      return KeyData.KeyMaterialType.ASYMMETRIC_PRIVATE;
    }
    if (type.equals(ProtoKeySerialization.KeyMaterialType.ASYMMETRIC_PUBLIC)) {
      return KeyData.KeyMaterialType.ASYMMETRIC_PUBLIC;
    }
    if (type.equals(ProtoKeySerialization.KeyMaterialType.REMOTE)) {
      return KeyData.KeyMaterialType.REMOTE;
    }
    throw new GeneralSecurityException("Unknown KeyMaterialType: " + type);
  }

  public static ProtoKeySerialization.KeyMaterialType fromProto(KeyData.KeyMaterialType type)
      throws GeneralSecurityException {
    switch (type) {
      case UNKNOWN_KEYMATERIAL:
        return ProtoKeySerialization.KeyMaterialType.UNKNOWN_KEYMATERIAL;
      case SYMMETRIC:
        return ProtoKeySerialization.KeyMaterialType.SYMMETRIC;
      case ASYMMETRIC_PRIVATE:
        return ProtoKeySerialization.KeyMaterialType.ASYMMETRIC_PRIVATE;
      case ASYMMETRIC_PUBLIC:
        return ProtoKeySerialization.KeyMaterialType.ASYMMETRIC_PUBLIC;
      case REMOTE:
        return ProtoKeySerialization.KeyMaterialType.REMOTE;
      case UNRECOGNIZED:
        throw new GeneralSecurityException("Unknown KeyMaterialType: " + type);
    }
    throw new GeneralSecurityException("Unknown KeyMaterialType: " + type);
  }

  public static ProtoKeySerialization.OutputPrefixType fromProto(OutputPrefixType type)
      throws GeneralSecurityException {
    switch (type) {
      case UNKNOWN_PREFIX:
        return ProtoKeySerialization.OutputPrefixType.UNKNOWN_PREFIX;
      case TINK:
        return ProtoKeySerialization.OutputPrefixType.TINK;
      case LEGACY:
        return ProtoKeySerialization.OutputPrefixType.LEGACY;
      case RAW:
        return ProtoKeySerialization.OutputPrefixType.RAW;
      case CRUNCHY:
        return ProtoKeySerialization.OutputPrefixType.CRUNCHY;
      case WITH_ID_REQUIREMENT:
        return ProtoKeySerialization.OutputPrefixType.WITH_ID_REQUIREMENT;
      case UNRECOGNIZED:
        throw new GeneralSecurityException("Unknown OutputPrefixType: " + type);
    }
    throw new GeneralSecurityException("Unknown OutputPrefixType: " + type);
  }

  public static OutputPrefixType toProto(ProtoKeySerialization.OutputPrefixType type)
      throws GeneralSecurityException {
    if (type.equals(ProtoKeySerialization.OutputPrefixType.UNKNOWN_PREFIX)) {
      return OutputPrefixType.UNKNOWN_PREFIX;
    }
    if (type.equals(ProtoKeySerialization.OutputPrefixType.TINK)) {
      return OutputPrefixType.TINK;
    }
    if (type.equals(ProtoKeySerialization.OutputPrefixType.LEGACY)) {
      return OutputPrefixType.LEGACY;
    }
    if (type.equals(ProtoKeySerialization.OutputPrefixType.RAW)) {
      return OutputPrefixType.RAW;
    }
    if (type.equals(ProtoKeySerialization.OutputPrefixType.CRUNCHY)) {
      return OutputPrefixType.CRUNCHY;
    }
    if (type.equals(ProtoKeySerialization.OutputPrefixType.WITH_ID_REQUIREMENT)) {
      return OutputPrefixType.WITH_ID_REQUIREMENT;
    }
    throw new GeneralSecurityException("Unknown OutputPrefixType: " + type);
  }

  /**
   * Returns the output prefix using the standard technique for protobuf based keys. Typically, this
   * should only be needed for legacy protobuf based keys.
   */
  public static Bytes getOutputPrefix(
      ProtoKeySerialization.OutputPrefixType type, @Nullable Integer idRequirement)
      throws GeneralSecurityException {
    if (type == ProtoKeySerialization.OutputPrefixType.RAW) {
      if (idRequirement != null) {
        throw new GeneralSecurityException("RAW output prefix type cannot have an id requirement");
      }
      return OutputPrefixUtil.EMPTY_PREFIX;
    }
    if (idRequirement == null) {
      throw new GeneralSecurityException("idRequirement must be non-null for " + type + " type");
    }
    if (type == ProtoKeySerialization.OutputPrefixType.TINK) {
      return OutputPrefixUtil.getTinkOutputPrefix(idRequirement);
    }
    if (type == ProtoKeySerialization.OutputPrefixType.LEGACY
        || type == ProtoKeySerialization.OutputPrefixType.CRUNCHY) {
      return OutputPrefixUtil.getLegacyOutputPrefix(idRequirement);
    }
    throw new GeneralSecurityException("Unknown OutputPrefixType: " + type);
  }

  private ProtoConversions() {}
}
