load("@rules_java//java:defs.bzl", "java_test")

licenses(["notice"])

java_test(
    name = "EcdsaSignerTest",
    size = "small",
    srcs = ["EcdsaSignerTest.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:public_key_sign",
        "//src/main/java/com/google/crypto/tink:public_key_verify",
        "//src/main/java/com/google/crypto/tink/signature:ecdsa_private_key",
        "//src/main/java/com/google/crypto/tink/signature/internal/testing:ecdsa_test_util",
        "//src/main/java/com/google/crypto/tink/signature/internal/testing:signature_test_vector",
        "//src/main/java/com/google/crypto/tink/signature/subtle:ecdsa_signer",
        "//src/main/java/com/google/crypto/tink/signature/subtle:ecdsa_verifier",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "EcdsaVerifierTest",
    size = "small",
    srcs = ["EcdsaVerifierTest.java"],
    data = ["//third_party/wycheproof:testvectors_v1"],
    deps = [
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:public_key_verify",
        "//src/main/java/com/google/crypto/tink/signature:ecdsa_parameters",
        "//src/main/java/com/google/crypto/tink/signature:ecdsa_private_key",
        "//src/main/java/com/google/crypto/tink/signature:ecdsa_public_key",
        "//src/main/java/com/google/crypto/tink/signature/internal/testing:ecdsa_test_util",
        "//src/main/java/com/google/crypto/tink/signature/internal/testing:signature_test_vector",
        "//src/main/java/com/google/crypto/tink/signature/subtle:ecdsa_verifier",
        "//src/main/java/com/google/crypto/tink/subtle:bytes",
        "//src/main/java/com/google/crypto/tink/subtle:hex",
        "//src/main/java/com/google/crypto/tink/testing:test_util",
        "//src/main/java/com/google/crypto/tink/testing:wycheproof_test_util",
        "@maven//:com_google_code_gson_gson",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "Ed25519VerifierTest",
    size = "small",
    srcs = ["Ed25519VerifierTest.java"],
    data = ["//third_party/wycheproof:testvectors_v1"],
    deps = [
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:public_key_verify",
        "//src/main/java/com/google/crypto/tink/signature:ed25519_private_key",
        "//src/main/java/com/google/crypto/tink/signature:ed25519_public_key",
        "//src/main/java/com/google/crypto/tink/signature/internal/testing:ed25519_test_util",
        "//src/main/java/com/google/crypto/tink/signature/internal/testing:signature_test_vector",
        "//src/main/java/com/google/crypto/tink/signature/subtle:ed25519_verifier",
        "//src/main/java/com/google/crypto/tink/subtle:bytes",
        "//src/main/java/com/google/crypto/tink/subtle:hex",
        "//src/main/java/com/google/crypto/tink/testing:wycheproof_test_util",
        "//src/main/java/com/google/crypto/tink/util:bytes",
        "@maven//:com_google_code_gson_gson",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "Ed25519SignerTest",
    size = "small",
    srcs = ["Ed25519SignerTest.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:public_key_sign",
        "//src/main/java/com/google/crypto/tink/signature:ed25519_private_key",
        "//src/main/java/com/google/crypto/tink/signature/internal/testing:ed25519_test_util",
        "//src/main/java/com/google/crypto/tink/signature/internal/testing:signature_test_vector",
        "//src/main/java/com/google/crypto/tink/signature/subtle:ed25519_signer",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "RsaSsaPkcs1SignerTest",
    size = "small",
    srcs = ["RsaSsaPkcs1SignerTest.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:public_key_sign",
        "//src/main/java/com/google/crypto/tink:public_key_verify",
        "//src/main/java/com/google/crypto/tink/config:tink_fips",
        "//src/main/java/com/google/crypto/tink/config/internal:tink_fips_util",
        "//src/main/java/com/google/crypto/tink/signature:rsa_ssa_pkcs1_private_key",
        "//src/main/java/com/google/crypto/tink/signature:rsa_ssa_pkcs1_public_key",
        "//src/main/java/com/google/crypto/tink/signature/internal/testing:rsa_ssa_pkcs1_test_util",
        "//src/main/java/com/google/crypto/tink/signature/internal/testing:signature_test_vector",
        "//src/main/java/com/google/crypto/tink/signature/subtle:rsa_ssa_pkcs1_signer",
        "//src/main/java/com/google/crypto/tink/signature/subtle:rsa_ssa_pkcs1_verifier",
        "//src/main/java/com/google/crypto/tink/subtle:bytes",
        "@maven//:junit_junit",
        "@maven//:org_conscrypt_conscrypt_openjdk_uber",
    ],
)

java_test(
    name = "RsaSsaPkcs1VerifierTest",
    size = "small",
    srcs = ["RsaSsaPkcs1VerifierTest.java"],
    data = ["//third_party/wycheproof:testvectors_v1"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:public_key_verify",
        "//src/main/java/com/google/crypto/tink/internal:util",
        "//src/main/java/com/google/crypto/tink/signature:rsa_ssa_pkcs1_parameters",
        "//src/main/java/com/google/crypto/tink/signature:rsa_ssa_pkcs1_public_key",
        "//src/main/java/com/google/crypto/tink/signature/internal/testing:rsa_ssa_pkcs1_test_util",
        "//src/main/java/com/google/crypto/tink/signature/internal/testing:signature_test_vector",
        "//src/main/java/com/google/crypto/tink/signature/subtle:rsa_ssa_pkcs1_verifier",
        "//src/main/java/com/google/crypto/tink/subtle:enums",
        "//src/main/java/com/google/crypto/tink/subtle:hex",
        "//src/main/java/com/google/crypto/tink/testing:wycheproof_test_util",
        "@maven//:com_google_code_gson_gson",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_conscrypt_conscrypt_openjdk_uber",
    ],
)

java_test(
    name = "RsaSsaPssSignerTest",
    size = "small",
    srcs = ["RsaSsaPssSignerTest.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:public_key_sign",
        "//src/main/java/com/google/crypto/tink:public_key_verify",
        "//src/main/java/com/google/crypto/tink/internal:util",
        "//src/main/java/com/google/crypto/tink/signature:rsa_ssa_pss_private_key",
        "//src/main/java/com/google/crypto/tink/signature/internal/testing:rsa_ssa_pss_test_util",
        "//src/main/java/com/google/crypto/tink/signature/internal/testing:signature_test_vector",
        "//src/main/java/com/google/crypto/tink/signature/subtle:rsa_ssa_pss_signer",
        "//src/main/java/com/google/crypto/tink/signature/subtle:rsa_ssa_pss_verifier",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_conscrypt_conscrypt_openjdk_uber",
    ],
)

java_test(
    name = "RsaSsaPssVerifierTest",
    size = "small",
    srcs = ["RsaSsaPssVerifierTest.java"],
    data = ["//third_party/wycheproof:testvectors_v1"],
    deps = [
        "//src/main/java/com/google/crypto/tink:public_key_verify",
        "//src/main/java/com/google/crypto/tink/internal:util",
        "//src/main/java/com/google/crypto/tink/signature:rsa_ssa_pss_parameters",
        "//src/main/java/com/google/crypto/tink/signature:rsa_ssa_pss_public_key",
        "//src/main/java/com/google/crypto/tink/signature/internal/testing:rsa_ssa_pss_test_util",
        "//src/main/java/com/google/crypto/tink/signature/internal/testing:signature_test_vector",
        "//src/main/java/com/google/crypto/tink/signature/subtle:rsa_ssa_pss_verifier",
        "//src/main/java/com/google/crypto/tink/subtle:bytes",
        "//src/main/java/com/google/crypto/tink/subtle:hex",
        "//src/main/java/com/google/crypto/tink/testing:wycheproof_test_util",
        "@maven//:com_google_code_gson_gson",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_conscrypt_conscrypt_openjdk_uber",
    ],
)

java_test(
    name = "MlDsaSignerTest",
    size = "small",
    srcs = ["MlDsaSignerTest.java"],
    data = ["//third_party/wycheproof:testvectors_v1"],
    deps = [
        "//src/main/java/com/google/crypto/tink:insecure_secret_key_access",
        "//src/main/java/com/google/crypto/tink:public_key_sign",
        "//src/main/java/com/google/crypto/tink:public_key_verify",
        "//src/main/java/com/google/crypto/tink/config/internal:tink_fips_util",
        "//src/main/java/com/google/crypto/tink/internal:tink_bug_exception",
        "//src/main/java/com/google/crypto/tink/signature:ml_dsa_parameters",
        "//src/main/java/com/google/crypto/tink/signature:ml_dsa_private_key",
        "//src/main/java/com/google/crypto/tink/signature:ml_dsa_public_key",
        "//src/main/java/com/google/crypto/tink/signature/internal:ml_dsa_verify_conscrypt",
        "//src/main/java/com/google/crypto/tink/signature/subtle:ml_dsa_signer",
        "//src/main/java/com/google/crypto/tink/signature/subtle:ml_dsa_verifier",
        "//src/main/java/com/google/crypto/tink/subtle:hex",
        "//src/main/java/com/google/crypto/tink/testing:wycheproof_test_util",
        "//src/main/java/com/google/crypto/tink/util:bytes",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes",
        "@maven//:com_google_code_gson_gson",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_conscrypt_conscrypt_openjdk_uber",
    ],
)

java_test(
    name = "MlDsaVerifierTest",
    size = "small",
    srcs = ["MlDsaVerifierTest.java"],
    data = ["//third_party/wycheproof:testvectors_v1"],
    deps = [
        "//src/main/java/com/google/crypto/tink:insecure_secret_key_access",
        "//src/main/java/com/google/crypto/tink:public_key_sign",
        "//src/main/java/com/google/crypto/tink:public_key_verify",
        "//src/main/java/com/google/crypto/tink/config/internal:tink_fips_util",
        "//src/main/java/com/google/crypto/tink/internal:tink_bug_exception",
        "//src/main/java/com/google/crypto/tink/signature:ml_dsa_parameters",
        "//src/main/java/com/google/crypto/tink/signature:ml_dsa_private_key",
        "//src/main/java/com/google/crypto/tink/signature:ml_dsa_public_key",
        "//src/main/java/com/google/crypto/tink/signature/internal:ml_dsa_verify_conscrypt",
        "//src/main/java/com/google/crypto/tink/signature/subtle:ml_dsa_signer",
        "//src/main/java/com/google/crypto/tink/signature/subtle:ml_dsa_verifier",
        "//src/main/java/com/google/crypto/tink/subtle:hex",
        "//src/main/java/com/google/crypto/tink/testing:wycheproof_test_util",
        "//src/main/java/com/google/crypto/tink/util:bytes",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes",
        "@maven//:com_google_code_gson_gson",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_conscrypt_conscrypt_openjdk_uber",
    ],
)

java_test(
    name = "SlhDsaSignerTest",
    size = "small",
    srcs = ["SlhDsaSignerTest.java"],
    data = ["//third_party/wycheproof:testvectors_v1"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:insecure_secret_key_access",
        "//src/main/java/com/google/crypto/tink:public_key_sign",
        "//src/main/java/com/google/crypto/tink:public_key_verify",
        "//src/main/java/com/google/crypto/tink/config/internal:tink_fips_util",
        "//src/main/java/com/google/crypto/tink/signature:slh_dsa_parameters",
        "//src/main/java/com/google/crypto/tink/signature:slh_dsa_private_key",
        "//src/main/java/com/google/crypto/tink/signature:slh_dsa_public_key",
        "//src/main/java/com/google/crypto/tink/signature/internal:slh_dsa_verify_conscrypt",
        "//src/main/java/com/google/crypto/tink/signature/subtle:slh_dsa_signer",
        "//src/main/java/com/google/crypto/tink/signature/subtle:slh_dsa_verifier",
        "//src/main/java/com/google/crypto/tink/subtle:hex",
        "//src/main/java/com/google/crypto/tink/util:bytes",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_conscrypt_conscrypt_openjdk_uber",
    ],
)

java_test(
    name = "SlhDsaVerifierTest",
    size = "small",
    srcs = ["SlhDsaVerifierTest.java"],
    data = ["//third_party/wycheproof:testvectors_v1"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:insecure_secret_key_access",
        "//src/main/java/com/google/crypto/tink:public_key_sign",
        "//src/main/java/com/google/crypto/tink:public_key_verify",
        "//src/main/java/com/google/crypto/tink/config/internal:tink_fips_util",
        "//src/main/java/com/google/crypto/tink/signature:slh_dsa_parameters",
        "//src/main/java/com/google/crypto/tink/signature:slh_dsa_private_key",
        "//src/main/java/com/google/crypto/tink/signature:slh_dsa_public_key",
        "//src/main/java/com/google/crypto/tink/signature/internal:slh_dsa_verify_conscrypt",
        "//src/main/java/com/google/crypto/tink/signature/subtle:slh_dsa_signer",
        "//src/main/java/com/google/crypto/tink/signature/subtle:slh_dsa_verifier",
        "//src/main/java/com/google/crypto/tink/subtle:hex",
        "//src/main/java/com/google/crypto/tink/util:bytes",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_conscrypt_conscrypt_openjdk_uber",
    ],
)

java_test(
    name = "RsaSsaPkcs1ProtoSerializationTest",
    size = "small",
    srcs = ["RsaSsaPkcs1ProtoSerializationTest.java"],
    deps = [
        "//proto:common_java_proto",
        "//proto:rsa_ssa_pkcs1_java_proto",
        "//proto:tink_java_proto",
        "//src/main/java/com/google/crypto/tink:insecure_secret_key_access",
        "//src/main/java/com/google/crypto/tink:key",
        "//src/main/java/com/google/crypto/tink:parameters",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization",
        "//src/main/java/com/google/crypto/tink/internal:proto_conversions",
        "//src/main/java/com/google/crypto/tink/internal/testing:asserts",
        "//src/main/java/com/google/crypto/tink/signature:rsa_ssa_pkcs1_parameters",
        "//src/main/java/com/google/crypto/tink/signature:rsa_ssa_pkcs1_private_key",
        "//src/main/java/com/google/crypto/tink/signature:rsa_ssa_pkcs1_public_key",
        "//src/main/java/com/google/crypto/tink/signature/subtle:rsa_ssa_pkcs1_proto_serialization",
        "//src/main/java/com/google/crypto/tink/subtle:base64",
        "//src/main/java/com/google/crypto/tink/subtle:hex",
        "//src/main/java/com/google/crypto/tink/util:secret_big_integer",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "RsaSsaPssProtoSerializationTest",
    size = "small",
    srcs = ["RsaSsaPssProtoSerializationTest.java"],
    deps = [
        "//proto:common_java_proto",
        "//proto:rsa_ssa_pss_java_proto",
        "//proto:tink_java_proto",
        "//src/main/java/com/google/crypto/tink:insecure_secret_key_access",
        "//src/main/java/com/google/crypto/tink:key",
        "//src/main/java/com/google/crypto/tink:parameters",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization",
        "//src/main/java/com/google/crypto/tink/internal:proto_conversions",
        "//src/main/java/com/google/crypto/tink/internal/testing:asserts",
        "//src/main/java/com/google/crypto/tink/signature:rsa_ssa_pss_parameters",
        "//src/main/java/com/google/crypto/tink/signature:rsa_ssa_pss_private_key",
        "//src/main/java/com/google/crypto/tink/signature:rsa_ssa_pss_public_key",
        "//src/main/java/com/google/crypto/tink/signature/subtle:rsa_ssa_pss_proto_serialization",
        "//src/main/java/com/google/crypto/tink/subtle:base64",
        "//src/main/java/com/google/crypto/tink/subtle:hex",
        "//src/main/java/com/google/crypto/tink/util:secret_big_integer",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)
