load("@rules_java//java:defs.bzl", "java_test")

licenses(["notice"])

package(default_visibility = ["//visibility:public"])

java_test(
    name = "AesCmacPrfTest",
    size = "small",
    srcs = ["AesCmacPrfTest.java"],
    data = ["//third_party/wycheproof:testvectors_v1"],
    deps = [
        "//src/main/java/com/google/crypto/tink:insecure_secret_key_access",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink/prf:aes_cmac_prf_key",
        "//src/main/java/com/google/crypto/tink/prf:aes_cmac_prf_parameters",
        "//src/main/java/com/google/crypto/tink/prf:prf_set",
        "//src/main/java/com/google/crypto/tink/prf/internal:aes_cmac_prf_test_util",
        "//src/main/java/com/google/crypto/tink/prf/internal:aes_cmac_prf_wycheproof_test_util",
        "//src/main/java/com/google/crypto/tink/prf/subtle:aes_cmac_prf",
        "//src/main/java/com/google/crypto/tink/subtle:hex",
        "//src/main/java/com/google/crypto/tink/subtle:random",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "HmacPrfTest",
    size = "small",
    srcs = ["HmacPrfTest.java"],
    tags = ["fips"],
    deps = [
        "//src/main/java/com/google/crypto/tink:insecure_secret_key_access",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:mac",
        "//src/main/java/com/google/crypto/tink/config:tink_fips",
        "//src/main/java/com/google/crypto/tink/config/internal:tink_fips_util",
        "//src/main/java/com/google/crypto/tink/prf:hmac_prf_key",
        "//src/main/java/com/google/crypto/tink/prf:hmac_prf_parameters",
        "//src/main/java/com/google/crypto/tink/prf:prf_set",
        "//src/main/java/com/google/crypto/tink/prf/subtle:hmac_prf",
        "//src/main/java/com/google/crypto/tink/subtle:hex",
        "//src/main/java/com/google/crypto/tink/subtle:prf_mac",
        "//src/main/java/com/google/crypto/tink/subtle:random",
        "//src/main/java/com/google/crypto/tink/testing:test_util",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes",
        "@maven//:junit_junit",
        "@maven//:org_conscrypt_conscrypt_openjdk_uber",
    ],
)

java_test(
    name = "HkdfPrfTest",
    size = "small",
    srcs = ["HkdfPrfTest.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:insecure_secret_key_access",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink/prf:hkdf_prf_key",
        "//src/main/java/com/google/crypto/tink/prf:hkdf_prf_parameters",
        "//src/main/java/com/google/crypto/tink/prf:prf_set",
        "//src/main/java/com/google/crypto/tink/prf/subtle:hkdf_prf",
        "//src/main/java/com/google/crypto/tink/subtle:enums",
        "//src/main/java/com/google/crypto/tink/subtle:hkdf",
        "//src/main/java/com/google/crypto/tink/subtle:random",
        "//src/main/java/com/google/crypto/tink/util:bytes",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "HmacPrfProtoSerializationTest",
    size = "small",
    srcs = ["HmacPrfProtoSerializationTest.java"],
    deps = [
        "//proto:common_java_proto",
        "//proto:hmac_prf_java_proto",
        "//src/main/java/com/google/crypto/tink:insecure_secret_key_access",
        "//src/main/java/com/google/crypto/tink:key",
        "//src/main/java/com/google/crypto/tink:parameters",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization",
        "//src/main/java/com/google/crypto/tink:secret_key_access",
        "//src/main/java/com/google/crypto/tink/internal/testing:asserts",
        "//src/main/java/com/google/crypto/tink/prf:hmac_prf_key",
        "//src/main/java/com/google/crypto/tink/prf:hmac_prf_parameters",
        "//src/main/java/com/google/crypto/tink/prf/subtle:hmac_prf_proto_serialization",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "HkdfPrfProtoSerializationTest",
    size = "small",
    srcs = ["HkdfPrfProtoSerializationTest.java"],
    deps = [
        "//proto:common_java_proto",
        "//proto:hkdf_prf_java_proto",
        "//src/main/java/com/google/crypto/tink:insecure_secret_key_access",
        "//src/main/java/com/google/crypto/tink:key",
        "//src/main/java/com/google/crypto/tink:parameters",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization",
        "//src/main/java/com/google/crypto/tink:secret_key_access",
        "//src/main/java/com/google/crypto/tink/internal/testing:asserts",
        "//src/main/java/com/google/crypto/tink/prf:hkdf_prf_key",
        "//src/main/java/com/google/crypto/tink/prf:hkdf_prf_parameters",
        "//src/main/java/com/google/crypto/tink/prf/subtle:hkdf_prf_proto_serialization",
        "//src/main/java/com/google/crypto/tink/subtle:hex",
        "//src/main/java/com/google/crypto/tink/util:bytes",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "AesCmacPrfProtoSerializationTest",
    size = "small",
    srcs = ["AesCmacPrfProtoSerializationTest.java"],
    deps = [
        "//proto:aes_cmac_prf_java_proto",
        "//src/main/java/com/google/crypto/tink:insecure_secret_key_access",
        "//src/main/java/com/google/crypto/tink:key",
        "//src/main/java/com/google/crypto/tink:parameters",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization",
        "//src/main/java/com/google/crypto/tink:secret_key_access",
        "//src/main/java/com/google/crypto/tink/internal/testing:asserts",
        "//src/main/java/com/google/crypto/tink/prf:aes_cmac_prf_key",
        "//src/main/java/com/google/crypto/tink/prf:aes_cmac_prf_parameters",
        "//src/main/java/com/google/crypto/tink/prf/subtle:aes_cmac_prf_proto_serialization",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

