load("@rules_android//android:rules.bzl", "android_library")
load("@rules_java//java:defs.bzl", "java_library")

licenses(["notice"])

package(default_visibility = ["//:__subpackages__"])

java_library(
    name = "rsa_kem_hybrid_encrypt",
    srcs = ["RsaKemHybridEncrypt.java"],
    deps = [
        ":rsa_kem",
        "//src/main/java/com/google/crypto/tink:aead",
        "//src/main/java/com/google/crypto/tink:hybrid_encrypt",
        "//src/main/java/com/google/crypto/tink/aead/subtle:aead_factory",
        "//src/main/java/com/google/crypto/tink/subtle:hkdf",
    ],
)

java_library(
    name = "rsa_kem",
    srcs = ["RsaKem.java"],
    deps = ["//src/main/java/com/google/crypto/tink/internal:big_integer_encoding"],
)

java_library(
    name = "rsa_kem_hybrid_decrypt",
    srcs = ["RsaKemHybridDecrypt.java"],
    deps = [
        ":rsa_kem",
        "//src/main/java/com/google/crypto/tink:aead",
        "//src/main/java/com/google/crypto/tink:hybrid_decrypt",
        "//src/main/java/com/google/crypto/tink/aead/subtle:aead_factory",
        "//src/main/java/com/google/crypto/tink/subtle:hkdf",
    ],
)

java_library(
    name = "hpke_proto_serialization",
    srcs = ["HpkeProtoSerialization.java"],
    deps = [
        "//proto:hpke_java_proto",
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization",
        "//src/main/java/com/google/crypto/tink:secret_key_access",
        "//src/main/java/com/google/crypto/tink/hybrid:hpke_parameters",
        "//src/main/java/com/google/crypto/tink/hybrid:hpke_private_key",
        "//src/main/java/com/google/crypto/tink/hybrid:hpke_public_key",
        "//src/main/java/com/google/crypto/tink/hybrid/internal:hpke_util",
        "//src/main/java/com/google/crypto/tink/internal:big_integer_encoding",
        "//src/main/java/com/google/crypto/tink/internal:enum_type_proto_converter",
        "//src/main/java/com/google/crypto/tink/util:bytes",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_errorprone_error_prone_annotations",
        "@maven//:com_google_protobuf_protobuf_java",
    ],
)

android_library(
    name = "hpke_proto_serialization-android",
    srcs = ["HpkeProtoSerialization.java"],
    deps = [
        "//proto:hpke_java_proto_lite",
        "//src/main/java/com/google/crypto/tink:accesses_partial_key-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization-android",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization-android",
        "//src/main/java/com/google/crypto/tink:secret_key_access-android",
        "//src/main/java/com/google/crypto/tink/hybrid:hpke_parameters-android",
        "//src/main/java/com/google/crypto/tink/hybrid:hpke_private_key-android",
        "//src/main/java/com/google/crypto/tink/hybrid:hpke_public_key-android",
        "//src/main/java/com/google/crypto/tink/hybrid/internal:hpke_util-android",
        "//src/main/java/com/google/crypto/tink/internal:big_integer_encoding-android",
        "//src/main/java/com/google/crypto/tink/internal:enum_type_proto_converter-android",
        "//src/main/java/com/google/crypto/tink/util:bytes-android",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes-android",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_errorprone_error_prone_annotations",
        "@maven//:com_google_protobuf_protobuf_javalite",
    ],
)

android_library(
    name = "rsa_kem-android",
    srcs = ["RsaKem.java"],
    deps = ["//src/main/java/com/google/crypto/tink/internal:big_integer_encoding-android"],
)

android_library(
    name = "rsa_kem_hybrid_decrypt-android",
    srcs = ["RsaKemHybridDecrypt.java"],
    deps = [
        ":rsa_kem-android",
        "//src/main/java/com/google/crypto/tink:aead-android",
        "//src/main/java/com/google/crypto/tink:hybrid_decrypt-android",
        "//src/main/java/com/google/crypto/tink/aead/subtle:aead_factory-android",
        "//src/main/java/com/google/crypto/tink/subtle:hkdf-android",
    ],
)

android_library(
    name = "rsa_kem_hybrid_encrypt-android",
    srcs = ["RsaKemHybridEncrypt.java"],
    deps = [
        ":rsa_kem-android",
        "//src/main/java/com/google/crypto/tink:aead-android",
        "//src/main/java/com/google/crypto/tink:hybrid_encrypt-android",
        "//src/main/java/com/google/crypto/tink/aead/subtle:aead_factory-android",
        "//src/main/java/com/google/crypto/tink/subtle:hkdf-android",
    ],
)
