load("@rules_android//android:rules.bzl", "android_library")
load("@rules_java//java:defs.bzl", "java_library")

licenses(["notice"])

package(default_visibility = ["//visibility:public"])

android_library(
    name = "aes_cmac_mac-android",
    srcs = ["AesCmacMac.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink:mac-android",
        "//src/main/java/com/google/crypto/tink/mac:aes_cmac_key-android",
        "//src/main/java/com/google/crypto/tink/subtle:prf_mac-android",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "aes_cmac_mac",
    srcs = ["AesCmacMac.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:mac",
        "//src/main/java/com/google/crypto/tink/mac:aes_cmac_key",
        "//src/main/java/com/google/crypto/tink/subtle:prf_mac",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "aes_cmac_chunked_mac-android",
    srcs = ["AesCmacChunkedMac.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink/mac:aes_cmac_key-android",
        "//src/main/java/com/google/crypto/tink/mac:chunked_mac-android",
        "//src/main/java/com/google/crypto/tink/mac/internal:chunked_aes_cmac_impl-android",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "aes_cmac_chunked_mac",
    srcs = ["AesCmacChunkedMac.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink/mac:aes_cmac_key",
        "//src/main/java/com/google/crypto/tink/mac:chunked_mac",
        "//src/main/java/com/google/crypto/tink/mac/internal:chunked_aes_cmac_impl",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "hmac_mac-android",
    srcs = ["HmacMac.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink:mac-android",
        "//src/main/java/com/google/crypto/tink/mac:hmac_key-android",
        "//src/main/java/com/google/crypto/tink/subtle:prf_mac-android",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "hmac_mac",
    srcs = ["HmacMac.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:mac",
        "//src/main/java/com/google/crypto/tink/mac:hmac_key",
        "//src/main/java/com/google/crypto/tink/subtle:prf_mac",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "hmac_chunked_mac-android",
    srcs = ["HmacChunkedMac.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink/mac:chunked_mac-android",
        "//src/main/java/com/google/crypto/tink/mac:hmac_key-android",
        "//src/main/java/com/google/crypto/tink/mac/internal:chunked_hmac_impl-android",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "hmac_chunked_mac",
    srcs = ["HmacChunkedMac.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink/mac:chunked_mac",
        "//src/main/java/com/google/crypto/tink/mac:hmac_key",
        "//src/main/java/com/google/crypto/tink/mac/internal:chunked_hmac_impl",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "hmac_proto_serialization",
    srcs = ["HmacProtoSerialization.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization",
        "//src/main/java/com/google/crypto/tink:secret_key_access",
        "//src/main/java/com/google/crypto/tink/mac:hmac_key",
        "//src/main/java/com/google/crypto/tink/mac:hmac_parameters",
        "//src/main/java/com/google/crypto/tink/mac/internal:hmac_proto_serialization",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "hmac_proto_serialization-android",
    srcs = ["HmacProtoSerialization.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization-android",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization-android",
        "//src/main/java/com/google/crypto/tink:secret_key_access-android",
        "//src/main/java/com/google/crypto/tink/mac:hmac_key-android",
        "//src/main/java/com/google/crypto/tink/mac:hmac_parameters-android",
        "//src/main/java/com/google/crypto/tink/mac/internal:hmac_proto_serialization-android",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "aes_cmac_proto_serialization",
    srcs = ["AesCmacProtoSerialization.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization",
        "//src/main/java/com/google/crypto/tink:secret_key_access",
        "//src/main/java/com/google/crypto/tink/mac:aes_cmac_key",
        "//src/main/java/com/google/crypto/tink/mac:aes_cmac_parameters",
        "//src/main/java/com/google/crypto/tink/mac/internal:aes_cmac_proto_serialization",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "aes_cmac_proto_serialization-android",
    srcs = ["AesCmacProtoSerialization.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization-android",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization-android",
        "//src/main/java/com/google/crypto/tink:secret_key_access-android",
        "//src/main/java/com/google/crypto/tink/mac:aes_cmac_key-android",
        "//src/main/java/com/google/crypto/tink/mac:aes_cmac_parameters-android",
        "//src/main/java/com/google/crypto/tink/mac/internal:aes_cmac_proto_serialization-android",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)
