load("@rules_android//android:rules.bzl", "android_library")
load("@rules_java//java:defs.bzl", "java_library")

licenses(["notice"])

package(default_visibility = ["//visibility:public"])

android_library(
    name = "deterministic_aeads-android",
    srcs = ["DeterministicAeads.java"],
    deps = ["//src/main/java/com/google/crypto/tink:deterministic_aead-android"],
)

java_library(
    name = "deterministic_aeads",
    srcs = ["DeterministicAeads.java"],
    deps = ["//src/main/java/com/google/crypto/tink:deterministic_aead"],
)

android_library(
    name = "aes_siv_deterministic_aead-android",
    srcs = ["AesSivDeterministicAead.java"],
    deps = [
        ":deterministic_aeads-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink/daead:aes_siv_key-android",
        "//src/main/java/com/google/crypto/tink/subtle:aes_siv-android",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "aes_siv_deterministic_aead",
    srcs = ["AesSivDeterministicAead.java"],
    deps = [
        ":deterministic_aeads",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink/daead:aes_siv_key",
        "//src/main/java/com/google/crypto/tink/subtle:aes_siv",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "aes_siv_proto_serialization",
    srcs = ["AesSivProtoSerialization.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization",
        "//src/main/java/com/google/crypto/tink:secret_key_access",
        "//src/main/java/com/google/crypto/tink/daead:aes_siv_key",
        "//src/main/java/com/google/crypto/tink/daead:aes_siv_parameters",
        "//src/main/java/com/google/crypto/tink/daead/internal:aes_siv_proto_serialization",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "aes_siv_proto_serialization-android",
    srcs = ["AesSivProtoSerialization.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization-android",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization-android",
        "//src/main/java/com/google/crypto/tink:secret_key_access-android",
        "//src/main/java/com/google/crypto/tink/daead:aes_siv_key-android",
        "//src/main/java/com/google/crypto/tink/daead:aes_siv_parameters-android",
        "//src/main/java/com/google/crypto/tink/daead/internal:aes_siv_proto_serialization-android",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)
