load("@rules_android//android:rules.bzl", "android_library")
load("@rules_java//java:defs.bzl", "java_library")

licenses(["notice"])

package(default_visibility = ["//:__subpackages__"])

java_library(
    name = "aead_factory",
    srcs = ["AeadFactory.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:aead",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "aes_gcm_factory",
    srcs = ["AesGcmFactory.java"],
    deps = [
        ":aead_factory",
        "//src/main/java/com/google/crypto/tink:aead",
        "//src/main/java/com/google/crypto/tink/subtle:aes_gcm_jce",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "aes_ctr_hmac_aead",
    srcs = ["AesCtrHmacAead.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:aead",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink/aead:aes_ctr_hmac_aead_key",
        "//src/main/java/com/google/crypto/tink/subtle:encrypt_then_authenticate",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "aes_eax_aead",
    srcs = ["AesEaxAead.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:aead",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink/aead:aes_eax_key",
        "//src/main/java/com/google/crypto/tink/subtle:aes_eax_jce",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "aes_gcm_aead",
    srcs = ["AesGcmAead.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:aead",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink/aead:aes_gcm_key",
        "//src/main/java/com/google/crypto/tink/subtle:aes_gcm_jce",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "aes_gcm_siv_aead",
    srcs = ["AesGcmSivAead.java"],
    deps = [
        ":aes_gcm_siv",
        "//src/main/java/com/google/crypto/tink:aead",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink/aead:aes_gcm_siv_key",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "cha_cha20_poly1305_aead",
    srcs = ["ChaCha20Poly1305Aead.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:aead",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink/aead:cha_cha20_poly1305_key",
        "//src/main/java/com/google/crypto/tink/aead/internal:cha_cha20_poly1305_jce",
        "//src/main/java/com/google/crypto/tink/subtle:cha_cha20_poly1305",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "x_cha_cha20_poly1305_aead",
    srcs = ["XChaCha20Poly1305Aead.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:aead",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink/aead:x_cha_cha20_poly1305_key",
        "//src/main/java/com/google/crypto/tink/aead/internal:x_cha_cha20_poly1305_jce",
        "//src/main/java/com/google/crypto/tink/subtle:x_cha_cha20_poly1305",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "x_aes_gcm_aead",
    srcs = ["XAesGcmAead.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:aead",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink/aead:x_aes_gcm_key",
        "//src/main/java/com/google/crypto/tink/aead/internal:x_aes_gcm",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "aes_gcm_siv",
    srcs = ["AesGcmSiv.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:aead",
        "//src/main/java/com/google/crypto/tink:insecure_secret_key_access",
        "//src/main/java/com/google/crypto/tink/aead:aes_gcm_siv_key",
        "//src/main/java/com/google/crypto/tink/aead:aes_gcm_siv_parameters",
        "//src/main/java/com/google/crypto/tink/aead/internal:aes_gcm_siv",
        "//src/main/java/com/google/crypto/tink/annotations:alpha",
        "//src/main/java/com/google/crypto/tink/subtle:subtle_util_cluster",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes",
        "@maven//:com_google_code_findbugs_jsr305",
    ],
)

android_library(
    name = "aead_factory-android",
    srcs = ["AeadFactory.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:aead-android",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "aes_ctr_hmac_aead-android",
    srcs = ["AesCtrHmacAead.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:aead-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink/aead:aes_ctr_hmac_aead_key-android",
        "//src/main/java/com/google/crypto/tink/subtle:encrypt_then_authenticate-android",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "aes_eax_aead-android",
    srcs = ["AesEaxAead.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:aead-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink/aead:aes_eax_key-android",
        "//src/main/java/com/google/crypto/tink/subtle:aes_eax_jce-android",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "aes_gcm_aead-android",
    srcs = ["AesGcmAead.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:aead-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink/aead:aes_gcm_key-android",
        "//src/main/java/com/google/crypto/tink/subtle:aes_gcm_jce-android",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "aes_gcm_siv_aead-android",
    srcs = ["AesGcmSivAead.java"],
    deps = [
        ":aes_gcm_siv-android",
        "//src/main/java/com/google/crypto/tink:aead-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink/aead:aes_gcm_siv_key-android",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "cha_cha20_poly1305_aead-android",
    srcs = ["ChaCha20Poly1305Aead.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:aead-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink/aead:cha_cha20_poly1305_key-android",
        "//src/main/java/com/google/crypto/tink/aead/internal:cha_cha20_poly1305_jce-android",
        "//src/main/java/com/google/crypto/tink/subtle:cha_cha20_poly1305-android",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "x_cha_cha20_poly1305_aead-android",
    srcs = ["XChaCha20Poly1305Aead.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:aead-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink/aead:x_cha_cha20_poly1305_key-android",
        "//src/main/java/com/google/crypto/tink/aead/internal:x_cha_cha20_poly1305_jce-android",
        "//src/main/java/com/google/crypto/tink/subtle:x_cha_cha20_poly1305-android",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "x_aes_gcm_aead-android",
    srcs = ["XAesGcmAead.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:aead-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink/aead:x_aes_gcm_key-android",
        "//src/main/java/com/google/crypto/tink/aead/internal:x_aes_gcm-android",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "aes_gcm_factory-android",
    srcs = ["AesGcmFactory.java"],
    deps = [
        ":aead_factory-android",
        "//src/main/java/com/google/crypto/tink:aead-android",
        "//src/main/java/com/google/crypto/tink/subtle:aes_gcm_jce-android",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "aes_gcm_siv-android",
    srcs = ["AesGcmSiv.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key-android",
        "//src/main/java/com/google/crypto/tink:aead-android",
        "//src/main/java/com/google/crypto/tink:insecure_secret_key_access-android",
        "//src/main/java/com/google/crypto/tink/aead:aes_gcm_siv_key-android",
        "//src/main/java/com/google/crypto/tink/aead:aes_gcm_siv_parameters-android",
        "//src/main/java/com/google/crypto/tink/aead/internal:aes_gcm_siv-android",
        "//src/main/java/com/google/crypto/tink/annotations:alpha-android",
        "//src/main/java/com/google/crypto/tink/subtle:subtle_util_cluster-android",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes-android",
        "@maven//:com_google_code_findbugs_jsr305",
    ],
)
