load("@rules_android//android:rules.bzl", "android_library")
load("@rules_java//java:defs.bzl", "java_library")

licenses(["notice"])

package(default_visibility = ["//visibility:public"])

android_library(
    name = "jwt_ecdsa_public_key_sign-android",
    srcs = ["JwtEcdsaPublicKeySign.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink:public_key_sign-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_ecdsa_private_key-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_public_key_sign-android",
        "//src/main/java/com/google/crypto/tink/jwt:raw_jwt-android",
        "//src/main/java/com/google/crypto/tink/jwt/internal:jwt_format-android",
        "//src/main/java/com/google/crypto/tink/subtle:ecdsa_sign_jce-android",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "jwt_ecdsa_public_key_sign",
    srcs = ["JwtEcdsaPublicKeySign.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:public_key_sign",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_ecdsa_private_key",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_public_key_sign",
        "//src/main/java/com/google/crypto/tink/jwt:raw_jwt",
        "//src/main/java/com/google/crypto/tink/jwt/internal:jwt_format",
        "//src/main/java/com/google/crypto/tink/subtle:ecdsa_sign_jce",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "jwt_ecdsa_public_key_verify",
    srcs = ["JwtEcdsaPublicKeyVerify.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:public_key_verify",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_ecdsa_public_key",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_public_key_verify",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_validator",
        "//src/main/java/com/google/crypto/tink/jwt:raw_jwt",
        "//src/main/java/com/google/crypto/tink/jwt:verified_jwt",
        "//src/main/java/com/google/crypto/tink/jwt/internal:json_util",
        "//src/main/java/com/google/crypto/tink/jwt/internal:jwt_format",
        "//src/main/java/com/google/crypto/tink/subtle:ecdsa_verify_jce",
        "@maven//:com_google_code_gson_gson",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "jwt_ecdsa_public_key_verify-android",
    srcs = ["JwtEcdsaPublicKeyVerify.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink:public_key_verify-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_ecdsa_public_key-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_public_key_verify-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_validator-android",
        "//src/main/java/com/google/crypto/tink/jwt:raw_jwt-android",
        "//src/main/java/com/google/crypto/tink/jwt:verified_jwt-android",
        "//src/main/java/com/google/crypto/tink/jwt/internal:json_util-android",
        "//src/main/java/com/google/crypto/tink/jwt/internal:jwt_format-android",
        "//src/main/java/com/google/crypto/tink/subtle:ecdsa_verify_jce-android",
        "@maven//:com_google_code_gson_gson",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "jwt_rsa_ssa_pkcs1_public_key_sign-android",
    srcs = ["JwtRsaSsaPkcs1PublicKeySign.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink:public_key_sign-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_public_key_sign-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_rsa_ssa_pkcs1_private_key-android",
        "//src/main/java/com/google/crypto/tink/jwt:raw_jwt-android",
        "//src/main/java/com/google/crypto/tink/jwt/internal:jwt_format-android",
        "//src/main/java/com/google/crypto/tink/subtle:rsa_ssa_pkcs1_sign_jce-android",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "jwt_rsa_ssa_pkcs1_public_key_sign",
    srcs = ["JwtRsaSsaPkcs1PublicKeySign.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:public_key_sign",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_public_key_sign",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_rsa_ssa_pkcs1_private_key",
        "//src/main/java/com/google/crypto/tink/jwt:raw_jwt",
        "//src/main/java/com/google/crypto/tink/jwt/internal:jwt_format",
        "//src/main/java/com/google/crypto/tink/subtle:rsa_ssa_pkcs1_sign_jce",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "jwt_rsa_ssa_pkcs1_public_key_verify",
    srcs = ["JwtRsaSsaPkcs1PublicKeyVerify.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:public_key_verify",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_public_key_verify",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_rsa_ssa_pkcs1_public_key",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_validator",
        "//src/main/java/com/google/crypto/tink/jwt:raw_jwt",
        "//src/main/java/com/google/crypto/tink/jwt:verified_jwt",
        "//src/main/java/com/google/crypto/tink/jwt/internal:json_util",
        "//src/main/java/com/google/crypto/tink/jwt/internal:jwt_format",
        "//src/main/java/com/google/crypto/tink/subtle:rsa_ssa_pkcs1_verify_jce",
        "@maven//:com_google_code_gson_gson",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "jwt_rsa_ssa_pkcs1_public_key_verify-android",
    srcs = ["JwtRsaSsaPkcs1PublicKeyVerify.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink:public_key_verify-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_public_key_verify-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_rsa_ssa_pkcs1_public_key-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_validator-android",
        "//src/main/java/com/google/crypto/tink/jwt:raw_jwt-android",
        "//src/main/java/com/google/crypto/tink/jwt:verified_jwt-android",
        "//src/main/java/com/google/crypto/tink/jwt/internal:json_util-android",
        "//src/main/java/com/google/crypto/tink/jwt/internal:jwt_format-android",
        "//src/main/java/com/google/crypto/tink/subtle:rsa_ssa_pkcs1_verify_jce-android",
        "@maven//:com_google_code_gson_gson",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "jwt_rsa_ssa_pss_public_key_sign-android",
    srcs = ["JwtRsaSsaPssPublicKeySign.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink:public_key_sign-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_public_key_sign-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_rsa_ssa_pss_private_key-android",
        "//src/main/java/com/google/crypto/tink/jwt:raw_jwt-android",
        "//src/main/java/com/google/crypto/tink/jwt/internal:jwt_format-android",
        "//src/main/java/com/google/crypto/tink/subtle:rsa_ssa_pss_sign_jce-android",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "jwt_rsa_ssa_pss_public_key_verify-android",
    srcs = ["JwtRsaSsaPssPublicKeyVerify.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink:public_key_verify-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_public_key_verify-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_rsa_ssa_pss_public_key-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_validator-android",
        "//src/main/java/com/google/crypto/tink/jwt:raw_jwt-android",
        "//src/main/java/com/google/crypto/tink/jwt:verified_jwt-android",
        "//src/main/java/com/google/crypto/tink/jwt/internal:json_util-android",
        "//src/main/java/com/google/crypto/tink/jwt/internal:jwt_format-android",
        "//src/main/java/com/google/crypto/tink/subtle:rsa_ssa_pss_verify_jce-android",
        "@maven//:com_google_code_gson_gson",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "jwt_rsa_ssa_pss_public_key_sign",
    srcs = ["JwtRsaSsaPssPublicKeySign.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:public_key_sign",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_public_key_sign",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_rsa_ssa_pss_private_key",
        "//src/main/java/com/google/crypto/tink/jwt:raw_jwt",
        "//src/main/java/com/google/crypto/tink/jwt/internal:jwt_format",
        "//src/main/java/com/google/crypto/tink/subtle:rsa_ssa_pss_sign_jce",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "jwt_rsa_ssa_pss_public_key_verify",
    srcs = ["JwtRsaSsaPssPublicKeyVerify.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:public_key_verify",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_public_key_verify",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_rsa_ssa_pss_public_key",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_validator",
        "//src/main/java/com/google/crypto/tink/jwt:raw_jwt",
        "//src/main/java/com/google/crypto/tink/jwt:verified_jwt",
        "//src/main/java/com/google/crypto/tink/jwt/internal:json_util",
        "//src/main/java/com/google/crypto/tink/jwt/internal:jwt_format",
        "//src/main/java/com/google/crypto/tink/subtle:rsa_ssa_pss_verify_jce",
        "@maven//:com_google_code_gson_gson",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "jwt_hmac-android",
    srcs = ["JwtHmac.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink:mac-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_hmac_key-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_hmac_parameters-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_mac-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_validator-android",
        "//src/main/java/com/google/crypto/tink/jwt:raw_jwt-android",
        "//src/main/java/com/google/crypto/tink/jwt:verified_jwt-android",
        "//src/main/java/com/google/crypto/tink/jwt/internal:json_util-android",
        "//src/main/java/com/google/crypto/tink/jwt/internal:jwt_format-android",
        "//src/main/java/com/google/crypto/tink/mac:hmac_key-android",
        "//src/main/java/com/google/crypto/tink/mac:hmac_parameters-android",
        "//src/main/java/com/google/crypto/tink/subtle:prf_mac-android",
        "@maven//:com_google_code_gson_gson",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "jwt_hmac",
    srcs = ["JwtHmac.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:mac",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_hmac_key",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_hmac_parameters",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_mac",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_validator",
        "//src/main/java/com/google/crypto/tink/jwt:raw_jwt",
        "//src/main/java/com/google/crypto/tink/jwt:verified_jwt",
        "//src/main/java/com/google/crypto/tink/jwt/internal:json_util",
        "//src/main/java/com/google/crypto/tink/jwt/internal:jwt_format",
        "//src/main/java/com/google/crypto/tink/mac:hmac_key",
        "//src/main/java/com/google/crypto/tink/mac:hmac_parameters",
        "//src/main/java/com/google/crypto/tink/subtle:prf_mac",
        "@maven//:com_google_code_gson_gson",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "jwt_ecdsa_proto_serialization",
    srcs = ["JwtEcdsaProtoSerialization.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization",
        "//src/main/java/com/google/crypto/tink:secret_key_access",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_ecdsa_parameters",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_ecdsa_private_key",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_ecdsa_public_key",
        "//src/main/java/com/google/crypto/tink/jwt/internal:jwt_ecdsa_proto_serialization",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "jwt_ecdsa_proto_serialization-android",
    srcs = ["JwtEcdsaProtoSerialization.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization-android",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization-android",
        "//src/main/java/com/google/crypto/tink:secret_key_access-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_ecdsa_parameters-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_ecdsa_private_key-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_ecdsa_public_key-android",
        "//src/main/java/com/google/crypto/tink/jwt/internal:jwt_ecdsa_proto_serialization-android",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "jwt_hmac_proto_serialization",
    srcs = ["JwtHmacProtoSerialization.java"],
    deps = [
        "//proto:jwt_hmac_java_proto",
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization",
        "//src/main/java/com/google/crypto/tink:secret_key_access",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_hmac_key",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_hmac_parameters",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_errorprone_error_prone_annotations",
        "@maven//:com_google_protobuf_protobuf_java",
    ],
)

android_library(
    name = "jwt_hmac_proto_serialization-android",
    srcs = ["JwtHmacProtoSerialization.java"],
    deps = [
        "//proto:jwt_hmac_java_proto_lite",
        "//src/main/java/com/google/crypto/tink:accesses_partial_key-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization-android",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization-android",
        "//src/main/java/com/google/crypto/tink:secret_key_access-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_hmac_key-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_hmac_parameters-android",
        "//src/main/java/com/google/crypto/tink/util:secret_bytes-android",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_errorprone_error_prone_annotations",
        "@maven//:com_google_protobuf_protobuf_javalite",
    ],
)

java_library(
    name = "jwt_rsa_ssa_pkcs1_proto_serialization",
    srcs = ["JwtRsaSsaPkcs1ProtoSerialization.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization",
        "//src/main/java/com/google/crypto/tink:secret_key_access",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_rsa_ssa_pkcs1_parameters",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_rsa_ssa_pkcs1_private_key",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_rsa_ssa_pkcs1_public_key",
        "//src/main/java/com/google/crypto/tink/jwt/internal:jwt_rsa_ssa_pkcs1_proto_serialization",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "jwt_rsa_ssa_pkcs1_proto_serialization-android",
    srcs = ["JwtRsaSsaPkcs1ProtoSerialization.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization-android",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization-android",
        "//src/main/java/com/google/crypto/tink:secret_key_access-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_rsa_ssa_pkcs1_parameters-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_rsa_ssa_pkcs1_private_key-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_rsa_ssa_pkcs1_public_key-android",
        "//src/main/java/com/google/crypto/tink/jwt/internal:jwt_rsa_ssa_pkcs1_proto_serialization-android",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

java_library(
    name = "jwt_rsa_ssa_pss_proto_serialization",
    srcs = ["JwtRsaSsaPssProtoSerialization.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization",
        "//src/main/java/com/google/crypto/tink:secret_key_access",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_rsa_ssa_pss_parameters",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_rsa_ssa_pss_private_key",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_rsa_ssa_pss_public_key",
        "//src/main/java/com/google/crypto/tink/jwt/internal:jwt_rsa_ssa_pss_proto_serialization",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)

android_library(
    name = "jwt_rsa_ssa_pss_proto_serialization-android",
    srcs = ["JwtRsaSsaPssProtoSerialization.java"],
    deps = [
        "//src/main/java/com/google/crypto/tink:accesses_partial_key-android",
        "//src/main/java/com/google/crypto/tink:low_level_crypto_caller-android",
        "//src/main/java/com/google/crypto/tink:proto_key_serialization-android",
        "//src/main/java/com/google/crypto/tink:proto_parameters_serialization-android",
        "//src/main/java/com/google/crypto/tink:secret_key_access-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_rsa_ssa_pss_parameters-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_rsa_ssa_pss_private_key-android",
        "//src/main/java/com/google/crypto/tink/jwt:jwt_rsa_ssa_pss_public_key-android",
        "//src/main/java/com/google/crypto/tink/jwt/internal:jwt_rsa_ssa_pss_proto_serialization-android",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_errorprone_error_prone_annotations",
    ],
)
